[2016-05-02 23:55:56,252] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:55:56,252] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:55:56,288] {models.py:296} INFO - Loaded DAG <DAG: extract_judges>
[2016-05-02 23:55:57,545] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:55:57,546] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:55:57,584] {models.py:296} INFO - Loaded DAG <DAG: extract_judges>
[2016-05-02 23:55:57,618] {models.py:1001} INFO - 
--------------------------------------------------------------------------------
Attempt 1 out of 2
--------------------------------------------------------------------------------

[2016-05-02 23:55:57,629] {models.py:1041} INFO - Executing <Task(PythonOperator): check_name_task> on 2016-04-05 00:00:00
[2016-05-02 23:55:57,635] {python_operator.py:66} INFO - Done. Returned value was: None
