[2016-05-02 23:57:08,933] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:57:08,933] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:57:09,124] {models.py:296} INFO - Loaded DAG <DAG: extract_judges>
[2016-05-02 23:57:13,990] {models.py:126} INFO - Filling up the DagBag from /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:57:13,990] {models.py:204} INFO - Importing /Users/bruno/Development/Intelivix/etl-example/dags/extract_judges.py
[2016-05-02 23:57:14,304] {models.py:296} INFO - Loaded DAG <DAG: extract_judges>
[2016-05-02 23:57:14,486] {models.py:1001} INFO - 
--------------------------------------------------------------------------------
Attempt 1 out of 2
--------------------------------------------------------------------------------

[2016-05-02 23:57:14,510] {models.py:1041} INFO - Executing <Task(PythonOperator): check_updates_with_judges> on 2016-04-20 00:00:00
[2016-05-02 23:57:14,521] {python_operator.py:66} INFO - Done. Returned value was: None
